# Generated by Django 2.0.5 on 2018-07-04 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=50)),
                ('login_time', models.IntegerField(default=24)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('update_ip', models.GenericIPAddressField(blank=True, null=True)),
            ],
        ),
    ]
