# Generated by Django 2.0.7 on 2018-07-05 23:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='last_ip',
        ),
        migrations.AddField(
            model_name='profile',
            name='last_login_ip',
            field=models.GenericIPAddressField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_logout',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 7, 5, 23, 48, 12, 362725)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='last_logout_ip',
            field=models.GenericIPAddressField(null=True),
        ),
    ]
